import Link from "next/link";

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-gradient-to-b from-black via-neutral-950 to-black text-white">
      <section className="mx-auto max-w-4xl px-6 py-12">
        <div className="mb-8 flex items-center justify-between">
          <Link
            href="/"
            className="rounded-full border border-white/10 bg-white/5 px-4 py-2 text-sm text-white/80 transition hover:border-white/20 hover:bg-white/10"
          >
            ← Back
          </Link>

          <div className="rounded-full border border-pink-500/20 bg-pink-500/10 px-4 py-2 text-xs font-medium uppercase tracking-[0.2em] text-pink-300">
            Privacy Policy
          </div>
        </div>

        <div className="rounded-[32px] border border-white/10 bg-white/[0.04] p-6 shadow-[0_0_0_1px_rgba(255,255,255,0.03),0_30px_80px_rgba(0,0,0,0.45)] backdrop-blur-xl md:p-8">
          <h1 className="text-4xl font-bold tracking-tight sm:text-5xl">
            Privacy Policy
          </h1>

          <p className="mt-4 text-white/65">
            Last updated: April 2026
          </p>

          <div className="mt-8 space-y-8 text-white/80">
            <section>
              <h2 className="text-2xl font-semibold text-white">1. Introduction</h2>
              <p className="mt-3 leading-8">
                This Privacy Policy explains how Viral Vibe Scanner collects, uses,
                and protects information when you use our website.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white">2. Information We Collect</h2>
              <p className="mt-3 leading-8">
                We may collect limited technical information such as browser type,
                device type, general analytics data, and interactions with the website.
              </p>
              <p className="mt-3 leading-8">
                If you upload an image, that image may be processed temporarily to
                generate your result. We do not intentionally collect sensitive personal
                data through normal use of the site.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white">3. How We Use Information</h2>
              <p className="mt-3 leading-8">
                We use information to operate the site, improve user experience,
                analyze performance, prevent abuse, and provide results generated by the app.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white">4. Cookies and Analytics</h2>
              <p className="mt-3 leading-8">
                We may use cookies, analytics tools, and advertising technologies
                to understand traffic and improve the website.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white">5. Advertising</h2>
              <p className="mt-3 leading-8">
                We may display third-party advertisements, including ads served by
                advertising partners such as Google AdSense. These providers may use
                cookies or similar technologies to personalize ads and measure performance.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white">6. Data Storage</h2>
              <p className="mt-3 leading-8">
                Uploaded files and technical data may be stored or processed by
                trusted third-party infrastructure providers used to operate the app.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white">7. Third-Party Services</h2>
              <p className="mt-3 leading-8">
                We may rely on third-party services for hosting, analytics, storage,
                and advertising. Their use of data is governed by their own policies.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white">8. Children’s Privacy</h2>
              <p className="mt-3 leading-8">
                This website is not intended for children under 13, and we do not knowingly
                collect personal data from children.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white">9. Your Rights</h2>
              <p className="mt-3 leading-8">
                Depending on your location, you may have rights to request access,
                correction, or deletion of your personal data where applicable.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white">10. Contact</h2>
              <p className="mt-3 leading-8">
                If you have questions about this Privacy Policy, you can contact us
                through the website or the contact method provided on our platform.
              </p>
            </section>
          </div>
        </div>
      </section>
    </main>
  );
}