import Link from "next/link";

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-gradient-to-b from-black via-neutral-950 to-black text-white">
      <section className="mx-auto max-w-4xl px-6 py-12">
        <div className="mb-8 flex items-center justify-between">
          <Link
            href="/"
            className="rounded-full border border-white/10 bg-white/5 px-4 py-2 text-sm text-white/80 transition hover:border-white/20 hover:bg-white/10"
          >
            ← Back
          </Link>

          <div className="rounded-full border border-pink-500/20 bg-pink-500/10 px-4 py-2 text-xs font-medium uppercase tracking-[0.2em] text-pink-300">
            Terms
          </div>
        </div>

        <div className="rounded-[32px] border border-white/10 bg-white/[0.04] p-6 shadow-[0_0_0_1px_rgba(255,255,255,0.03),0_30px_80px_rgba(0,0,0,0.45)] backdrop-blur-xl md:p-8">
          <h1 className="text-4xl font-bold tracking-tight sm:text-5xl">
            Terms & Conditions
          </h1>

          <p className="mt-4 text-white/65">
            Last updated: April 2026
          </p>

          <div className="mt-8 space-y-8 text-white/80">
            <section>
              <h2 className="text-2xl font-semibold text-white">1. Acceptance of Terms</h2>
              <p className="mt-3 leading-8">
                By accessing or using Viral Vibe Scanner, you agree to these Terms
                and Conditions. If you do not agree, please do not use the website.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white">2. Use of the Service</h2>
              <p className="mt-3 leading-8">
                This website is provided for entertainment, informational, and general
                user experience purposes. Results generated by the app should not be
                interpreted as factual, professional, medical, legal, or psychological advice.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white">3. User Content</h2>
              <p className="mt-3 leading-8">
                If you upload an image or other content, you confirm that you have the
                right to use it and that it does not violate applicable laws or third-party rights.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white">4. Prohibited Use</h2>
              <p className="mt-3 leading-8">
                You agree not to misuse the website, attempt unauthorized access,
                upload unlawful content, disrupt the service, or use the platform for
                abusive, fraudulent, or harmful purposes.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white">5. Intellectual Property</h2>
              <p className="mt-3 leading-8">
                The website design, branding, features, and original content are owned
                by the platform operator unless otherwise stated. You may not copy,
                reproduce, or commercially exploit them without permission.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white">6. No Guarantees</h2>
              <p className="mt-3 leading-8">
                We do not guarantee that the website will always be available,
                uninterrupted, error-free, or that results will meet any specific expectations.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white">7. Limitation of Liability</h2>
              <p className="mt-3 leading-8">
                To the maximum extent permitted by law, we are not liable for indirect,
                incidental, special, or consequential damages resulting from the use
                or inability to use the website.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white">8. Third-Party Services</h2>
              <p className="mt-3 leading-8">
                The website may use third-party providers for hosting, analytics,
                payments, storage, and advertising. We are not responsible for the
                independent policies or actions of those third parties.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white">9. Changes to Terms</h2>
              <p className="mt-3 leading-8">
                We may update these Terms at any time. Continued use of the website
                after changes are published means you accept the updated Terms.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white">10. Contact</h2>
              <p className="mt-3 leading-8">
                For questions regarding these Terms, please contact us through the
                website or the contact details provided by the platform operator.
              </p>
            </section>
          </div>
        </div>
      </section>
    </main>
  );
}